# Generated by Django 6.0.5 on 2026-06-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Televisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, verbose_name='Mac Address')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Serial Number')),
                ('lock_status', models.BooleanField(default=False, verbose_name='Lock Status')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Invoice Date')),
                ('due_status', models.BooleanField(default=False, help_text='True si la factura está vencida, False si no.', verbose_name='Due Status')),
                ('correo_persona', models.EmailField(max_length=254, verbose_name='Correo persona')),
                ('nombre_persona', models.CharField(max_length=150, verbose_name='Nombre persona')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'televisor',
                'verbose_name_plural': 'televisores',
            },
        ),
    ]
