# Generated by Django 6.0.5 on 2026-06-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whaletv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='televisor',
            name='mac_address',
            field=models.CharField(max_length=50, verbose_name='Mac Address'),
        ),
    ]
