# Generated by Django 6.0.5 on 2026-06-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whaletv', '0002_alter_televisor_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='televisor',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
    ]
