# Generated by Django 6.0.5 on 2026-06-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whaletv', '0003_televisor_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='televisor',
            name='due_status',
            field=models.BooleanField(default=False, help_text='Automático: True si la factura está vencida y sin pagar.', verbose_name='Due Status'),
        ),
    ]
