# Generated by Django 6.0.5 on 2026-06-09 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whaletv', '0004_alter_televisor_due_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='televisor',
            name='due_status',
        ),
        migrations.RemoveField(
            model_name='televisor',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='televisor',
            name='pago',
        ),
        migrations.AddField(
            model_name='televisor',
            name='numero_cuotas',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de cuotas'),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, verbose_name='Número de factura')),
                ('numero_cuota', models.PositiveIntegerField(default=1, verbose_name='Número de cuota')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('pagada', models.BooleanField(default=False, verbose_name='Pagada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('televisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='whaletv.televisor', verbose_name='televisor')),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'facturas',
                'ordering': ['numero_cuota', 'fecha_vencimiento'],
            },
        ),
    ]
