# Generated by Django 6.0.5 on 2026-06-09 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whaletv', '0005_remove_televisor_due_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('corriendo', 'Corriendo'), ('terminado', 'Terminado'), ('error', 'Error')], default='pendiente', max_length=12)),
                ('total', models.PositiveIntegerField(default=0)),
                ('workers', models.PositiveIntegerField(default=4)),
                ('error', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('terminado', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'sincronización',
                'verbose_name_plural': 'sincronizaciones',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='SyncJobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ok', 'OK'), ('error', 'Error')], default='pendiente', max_length=10)),
                ('aplicado', models.BooleanField(default=False)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='whaletv.syncjob')),
                ('televisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whaletv.televisor')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
