# Generated by Django 6.0.5 on 2026-06-11 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whaletv', '0006_syncjob_syncjobitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='syncjob',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_jobs', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='usuario_email',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Correo de quien sincronizó'),
        ),
        migrations.CreateModel(
            name='RegistroSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_email', models.CharField(blank=True, default='', max_length=254, verbose_name='Correo')),
                ('nombre_persona', models.CharField(blank=True, default='', max_length=150, verbose_name='Nombre persona')),
                ('mac_address', models.CharField(max_length=50, verbose_name='Mac Address')),
                ('lock_status', models.BooleanField(default=False, verbose_name='Quedó bloqueado')),
                ('aplicado', models.BooleanField(default=False, verbose_name='Aplicó cambio en el portal')),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('masivo', 'Masivo')], default='individual', max_length=12)),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('televisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_sync', to='whaletv.televisor', verbose_name='televisor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_sync', to=settings.AUTH_USER_MODEL, verbose_name='quién sincronizó')),
            ],
            options={
                'verbose_name': 'registro de sincronización',
                'verbose_name_plural': 'registros de sincronización',
                'ordering': ['-creado'],
            },
        ),
    ]
