# Generated by Django 6.0.5 on 2026-06-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whaletv', '0007_syncjob_usuario_syncjob_usuario_email_registrosync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncjob',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('corriendo', 'Corriendo'), ('terminado', 'Terminado'), ('error', 'Error'), ('cancelado', 'Cancelado')], default='pendiente', max_length=12),
        ),
    ]
