# Generated by Django 6.0.5 on 2026-06-16 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whaletv', '0008_alter_syncjob_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinCodeGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_email', models.CharField(blank=True, default='', max_length=254, verbose_name='Correo')),
                ('mac_address', models.CharField(max_length=50, verbose_name='Mac Address')),
                ('passcode', models.CharField(max_length=100, verbose_name='Passcode')),
                ('pin_code', models.CharField(max_length=100, verbose_name='Pin Code')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pincodes', to=settings.AUTH_USER_MODEL, verbose_name='quién lo generó')),
            ],
            options={
                'verbose_name': 'pin code generado',
                'verbose_name_plural': 'pin codes generados',
                'ordering': ['-creado'],
            },
        ),
    ]
