# Generated by Django 6.0.5 on 2026-06-22 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whaletv', '0009_pincodegenerado'),
    ]

    operations = [
        migrations.AddField(
            model_name='televisor',
            name='numero_credito',
            field=models.CharField(blank=True, default='', max_length=60, validators=[django.core.validators.RegexValidator('^\\d{1,60}$', 'El número de crédito debe contener solo dígitos (máximo 60).')], verbose_name='Número de crédito'),
        ),
    ]
