# Generated by Django 6.0.5 on 2026-06-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whaletv', '0010_televisor_numero_credito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='televisor',
            name='correo_persona',
        ),
        migrations.RemoveField(
            model_name='televisor',
            name='nombre_persona',
        ),
        migrations.RemoveField(
            model_name='televisor',
            name='numero_cuotas',
        ),
    ]
