# Generated by Django 6.0.5 on 2026-06-22 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whaletv', '0011_remove_televisor_correo_persona_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Serial Number')),
                ('mac_address', models.CharField(max_length=50, verbose_name='Mac Address')),
                ('estado', models.BooleanField(default=False, verbose_name='Bloqueado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('televisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='whaletv.televisor', verbose_name='televisor')),
            ],
            options={
                'verbose_name': 'bloqueo',
                'verbose_name_plural': 'bloqueos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
