# Generated by Django 6.0.5 on 2026-06-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whaletv', '0012_bloqueo_delete_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='televisor',
            name='mac_address',
            field=models.CharField(max_length=50, verbose_name='Dirección MAC'),
        ),
        migrations.AlterField(
            model_name='televisor',
            name='serial_number',
            field=models.CharField(max_length=50, verbose_name='Número de serie'),
        ),
    ]
