# Generated by Django 6.0.5 on 2026-06-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whaletv', '0013_alter_televisor_mac_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncjob',
            name='tipo',
            field=models.CharField(choices=[('sincronizacion', 'Sincronización'), ('validacion', 'Validación')], default='sincronizacion', max_length=14),
        ),
        migrations.AddField(
            model_name='syncjobitem',
            name='coincide',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncjobitem',
            name='local_bloqueado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncjobitem',
            name='remoto_bloqueado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
