# Generated by Django 6.0.5 on 2026-06-23 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whaletv', '0015_rename_bloqueo_inhabilitacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inhabilitacion',
            options={'ordering': ['-created_at'], 'verbose_name': 'inhabilitación', 'verbose_name_plural': 'inhabilitaciones'},
        ),
        migrations.AlterField(
            model_name='inhabilitacion',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Inhabilitado'),
        ),
        migrations.AlterField(
            model_name='inhabilitacion',
            name='televisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inhabilitaciones', to='whaletv.televisor', verbose_name='televisor'),
        ),
        migrations.AlterField(
            model_name='registrosync',
            name='inhabilitado',
            field=models.BooleanField(default=False, verbose_name='Quedó inhabilitado'),
        ),
        migrations.AlterField(
            model_name='televisor',
            name='inhabilitado',
            field=models.BooleanField(default=False, verbose_name='Inhabilitado'),
        ),
    ]
